[package]
name = "tari_payment_engine"
version = "0.1.0"
edition = "2021"
description = "Database backend for Tari payment gateway"

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
log = "0.4.17"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sqlx = { version = "0.7.3", features = ["runtime-tokio", "chrono"] }
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
regex = "1.10.3"
tari_common_types = "1.0.0-pre.10"

[features]
default = ["sqlite"]
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]
libtest = ["cucumber/libtest"]

[dev-dependencies]
dotenvy = "0.15.0"
env_logger = "0.11.3"
cucumber = { version = "0.20", features = ["libtest"] }
futures-util = "0.3.30"
once_cell = "1.19.0"
rand = "0.8.5"

[[test]]
name = "order_flow" # this should be the same as the filename of your test target
harness = false  # allows Cucumber to print output instead of libtest
